### ISSUE TITLE
в sdk работает загрузка? 

### ISSUE THREAD

**Issue by rik43** [Friday14/cloud-mail-ru#2]
Добрый день, пробую использовать библиотеку. 

тестовый код
```
$cloud = new \Friday14\Mailru\Cloud('xxx', 'xxx', 'inbox.ru');
$files = $cloud->files('/'); // работает
$cloud->createFile('/1.txt','Hello World'); // не работает
```

выдает ошибку
```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://cloclo3-upload.cloud.mail.ru/upload/?cloud_domain=2&x-email=lexxxx%40inbox.ru&fileapi15004124608926=` resulted in a `404 Not Found` response:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr> (truncated...)
 in ...\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 ...\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create() #1 ...\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 ...\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 ...\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise in ...\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
```

могу дать доступ к тестовому акк.

**Comment by em7v** [comment]
Здравствуйте, в данный момент я не поддерживаю этот пакет. В описании добавил памятку deprecated. 
Хотел бы вам помочь, но боюсь загрузка мне не позволит вернуть пакет к жизни. Если все таки удастся найти время, обязательно напишу вам.

**Comment by rik43** [comment]
понятно, в любом случае спасибо за ответ. отрицательный результат тоже результат. 
вашу библиотеку использовал косвенно, она используется в зависимостях https://github.com/freecod/flysystem-mailru-cloud
